# change checklistIss to your domain value
tokenConfig: |
  {
    "ttl": "1h"
  }

tokenImage: "docker.io/webngt/token-endpoint:0.0.6"
resultsImage: "docker.io/webngt/ka-results-service:0.0.20"

# redefine for your environment
ingressHostName: checklist.webngt.com

# if true generate istio crds
# istio crds depend on cert-manager certificates deployed in release namespace !!!!
useIstio: true