{{ if .Values.useIstio }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.ingressHostName }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert-webngt-wildcard
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-token-vs
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - {{ .Values.ingressHostName }}
  http:
  - match:
    - uri:
        prefix: /tokens
    route:
    - destination:
        host: {{ .Release.Name }}-token-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-save-vs
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - {{ .Values.ingressHostName }}
  http:
  - match:
    - uri:
        prefix: /save
    route:
    - destination:
        host: {{ .Release.Name }}-results-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-report-vs
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - {{ .Values.ingressHostName }}
  http:
  - match:
    - uri:
        prefix: /report
    route:
    - destination:
        host: {{ .Release.Name }}-results-service
        port:
          number: 80
{{ end }}
